---
- name: Lesson 9
  hosts: NFS-Server
  gather_facts: false
  become: true
  become_user: root
  become_method: sudo

  vars:
    client_ip: '192.168.50.11/32' #указать ip клиентской машины

  tasks:
    - name: install nfs server
      ansible.builtin.apt:
        name: nfs-kernel-server
        state: latest

    - name: Create sharing folder
      ansible.builtin.file:
        path: /srv/share/upload
        state: directory
        owner: nobody
        group: nogroup
        mode: '0777'
    
    # - name: clear file export
    #   ansible.builtin.shell:
    #     "> /etc/exports"

    - name: add client to export config
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: "/srv/share {{ client_ip }}(rw,sync,root_squash)"
        state: present
    
    - name: export directory
      ansible.builtin.shell: "exportfs -r"

    - name: Chek export
      ansible.builtin.shell:
        "exportfs -s"
      register: check
    
    - name: show check
      debug:
        msg: "{{ check }}"
    
    - name: create test file  
      ansible.builtin.file:
        path: "/srv/share/upload/check_file"
        state: touch

- name: Lesson 9
  hosts: NFS-Client
  gather_facts: false
  become: true
  become_user: root
  become_method: sudo

  vars:
    server_ip: '192.168.50.10' #указать ip серверной машины

  tasks:
    - name: install nfs client
      ansible.builtin.apt:
        name: nfs-common
        state: latest

    - name: add client to export config
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "{{ server_ip }}:/srv/share/ /mnt nfs vers=3,noauto,x-systemd.automount 0 0"
        state: present
    
    - name: Reload deamon
      ansible.builtin.systemd_service:
        daemon_reload: true
    
    - name: Reload sremote-fs.target 
      ansible.builtin.systemd_service:
        name: remote-fs.target
        state: restarted

    - name: check connect
      ansible.builtin.shell:
        "mount | grep mnt"
      register: check_connect
    
    - name: show check_connect
      debug:
        msg: "{{ check_connect }}"
    
    - name: create test file  
      ansible.builtin.file:
        path: "/mnt/upload/client_file"
        state: touch
    
    - name: list files in /mnt  
      ansible.builtin.shell:  'ls /mnt/upload'
      register: list_files

    - name: show files
      debug:
        msg: '{{ list_files }}'
